var General = require('./models/general_info');
const mongoose = require('mongoose');
mongoose.connect('mongodb://localhost:27017/EUsongbook');

let theGeneralInfo = new General({

    contact_name: "Jeppe Marsling",
    contact_phone: "+45 7154 1361",
    contact_mail: "editor@eu-songbook.org",
    mission_statement: "As the name reveals, the European Union Songbook organisation was founded in Copenhagen 2015 with one aim: to organise The European Union Songbook together with qualified music teachers, music students and choir singers – and to distribute it as cheaply as possible. We firmly believe that creation of such a union songbook should involve people from all member states – and that this cooperation should have no ties to the political establishment of the EU. The European Union is not a location in Brussels or Strasbourg – it is front and foremost the peoples of Europe. We don’t feel there is a contradiction between nation and union, national culture and European culture; we see them as complements. More than anything else, European culture is the exchange of national cultures. For more than 50 years, we, the European citizens, have exchanged physical things: coal, fish and other products. The cultural exchange on the other hand, has so far consisted mainly in sports – Champions League – and a single song contest – The Eurovision. We feel time has come to create a more lasting common symbol, a songbook. Even though music truly is a universal language, merely reading the sheet music for the 162 songs to be printed in the songbook is not culturally satisfactory: therefore the lyrics will be printed in an English translation as well as in the 24 EU languages, side by side. This will enable all users of the songbook to sing along. Even though English is spoken by almost 40 percent of the European population, all citizens should have the option to sing the 162 songs in their national languages. Therefore, the income generated by the first version in 2019 will finance 27 national versions of the European Union Songbook. We hope to make the creation of The European Union Songbook a recurring event, so that musicians, music teachers and music students throughout the union can vote on the content every four years. Let us both share and learn about the 27 national song treasures in EU. Let’s sing together!",
    statutes: "http://www.eu-songbook.org/wp-content/uploads/2015/01/Vedt%C3%A6gter_for_Foreningen_for_Den_Europ%C3%A6iske_Unions_Sangbog.pdf"

});

theGeneralInfo.save(err =>{
    if (err) throw err;
    console.log("General Info saved to database");
});
